### ISSUE TITLE
Create Graph Representation From Google Earth File

### ISSUE THREAD

**Issue by RayyanZaid** [RayyanZaid/ucr-pathfinder-backend#23]
Use the Node and Edge class to create a graph.  Use the class diagram.

Prerequisites 
- [x] Node automation is finished  #19 
- [ ] Edge Class is finished #20 
- [x] At least 3 nodes are on the Google Earth. (Should add more) #18
